name: Tests and Deploy

on:
  push:
    branches:
      - "main"

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Install packeges
        run: pip install editorconfig-checker;
          sudo apt install ssh -y

      - name: Run tests
        run: editorconfig-checker *
      - name: SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
      - name: Test SSH
        run: ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}
