name: Tests and Deploy

on:
  push:
    branches:
      - "main"

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Install packeges
        run: pip install editorconfig-checker;

      - name: Run tests
        run: editorconfig-checker *

        uses: garygrossgarten/github-action-scp@release
        with:
          local: src
          remote: var/www
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PWD }}
