name: Tests and Deploy

on:
  push:
    tags:
      - "*"
    branches:
      - "*"

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: touch a.txt
