name: Tests and Deploy

on:
  push:
    tags:
      - "*"
    branches:
      - "*"

jobs:
  run_tests:
    runs-on: "ubuntu-latest"
    steps:
      # Чекаутим код
      - name: Check Out Repo
      - uses: actions/checkout@v2
