name: Tests and Deploy

on:
  push:
    branches:
      - "main"

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Install Packeges
        run: pip install editorconfig-checker;

      - name: Run tests
        run: editorconfig-checker *

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PWD }}
          port: 22
          source: "./"
          target: "/var/www"
          rm: "true"

      - name: Scriptos por Remote Server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /var/www;
            python3 -m venv env;
            source env/bin/activate;
            pip3 install -r requirements.txt;
            python3 grand_core_bot.py;

          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PWD }}
