name: Tests and Deploy

on:
  push:
    branches:
      - "main"

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Install packeges
        run: pip install editorconfig-checker;
          sudo apt install ssh -y

      - name: Run tests
        run: editorconfig-checker *

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PWD }}
          port: 22
          source: "src"
          target: "src"
          rm: "true"
