name: Tests and Deploy

on:
  push:
    branches:
      - "main"

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Install packeges
        run: pip install editorconfig-checker;
          sudo apt-get install sshfs;

      - name: Run tests
        run: editorconfig-checker *

      - name: Deploy to Server
        run: mkdir ~/.ssh;
          cd ~/.ssh;
          echo "${{ secrets.SERVER_SSH_KEY }}" > id_rsa;
          sshfs -ononempty ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:src /var/www
